language: node_js

sudo: false

node_js:
    - 8

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - rvm install 2.2.2
    - bundle install

script: gulp default --ci

branches:
    only:
      - master

addons:
    firefox: latest
