language: node_js
node_js:
  - 6
cache: yarn
env:
  global:
    - NODE_ENV=test
script:
  - yarn run lint
  - yarn run test -- --coverage
  - NODE_ENV=production yarn run webpack
after_success:
  - bash <(curl -s https://codecov.io/bash)
